-- SLSWCA database setup — generated by scripts/bundle-sql.sh. Run ONCE on a fresh project.
-- Supabase → SQL Editor → New query → paste all → Run.
begin;

-- ===== migrations/20260930000000_init.sql
-- SLSWCA initial schema.
-- Principles:
--   * RLS on every table. Public content is read-only for anon.
--   * Anything involving money or identity is written only by the server
--     (service_role bypasses RLS); clients never insert payments directly.
--   * Users can never escalate their own role (column-level grants).

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- enums
create type public.member_role as enum ('member', 'coach', 'admin');
create type public.event_kind as enum ('competition', 'workshop');
create type public.event_status as enum ('draft', 'published', 'cancelled');
create type public.registration_status as enum ('pending', 'confirmed', 'cancelled');
create type public.academy_pathway as enum ('Coaching', 'Officiating', 'Athlete Development');
create type public.payment_purpose as enum ('contribution', 'registration', 'booking');
create type public.payment_status as enum ('pending', 'success', 'failed', 'cancelled', 'chargedback');
create type public.contribution_fund as enum ('general', 'youth', 'equipment', 'team_travel');

-- ---------------------------------------------------------------- helpers
create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- ---------------------------------------------------------------- clubs
create table public.clubs (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name text not null,
  city text,
  instagram text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- profiles
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text check (char_length(full_name) <= 120),
  phone text check (char_length(phone) <= 24),
  club_id uuid references public.clubs (id) on delete set null,
  role public.member_role not null default 'member',
  coach_tier text check (coach_tier in ('tier-3', 'tier-2', 'tier-1', 'master')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

-- Auto-create a profile for every new auth user.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, left(new.raw_user_meta_data ->> 'full_name', 120));
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- security definer so policies can call it without recursive RLS on profiles.
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles where id = (select auth.uid()) and role = 'admin'
  );
$$;

-- ---------------------------------------------------------------- events
create table public.events (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  kind public.event_kind not null,
  status public.event_status not null default 'draft',
  title text not null,
  body text not null default '',
  venue text,
  starts_at timestamptz,
  fee_lkr numeric(12, 2) not null default 0 check (fee_lkr >= 0),
  capacity int check (capacity > 0),
  categories text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger events_touch before update on public.events
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------- payments
create table public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id text not null unique,               -- sent to PayHere
  purpose public.payment_purpose not null,
  user_id uuid references auth.users (id) on delete set null,
  amount numeric(12, 2) not null check (amount > 0),
  currency text not null default 'LKR' check (currency = 'LKR'),
  recurring boolean not null default false,
  status public.payment_status not null default 'pending',
  provider text not null default 'payhere',
  provider_payment_id text,
  method text,
  status_message text,
  raw_notify jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index payments_user_idx on public.payments (user_id);
create trigger payments_touch before update on public.payments
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------- registrations
create table public.event_registrations (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events (id) on delete restrict,
  user_id uuid not null references auth.users (id) on delete cascade,
  category text,
  club_id uuid references public.clubs (id) on delete set null,
  waiver_accepted_at timestamptz not null,
  status public.registration_status not null default 'pending',
  payment_id uuid references public.payments (id) on delete set null,
  ticket_code text unique default encode(gen_random_bytes(12), 'hex'),
  created_at timestamptz not null default now(),
  unique (event_id, user_id)
);

-- ---------------------------------------------------------------- contributions
create table public.contributions (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null unique references public.payments (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  fund public.contribution_fund not null default 'general',
  donor_name text not null check (char_length(donor_name) between 2 and 120),
  donor_email text not null check (char_length(donor_email) <= 254),
  donor_phone text check (char_length(donor_phone) <= 24),
  anonymous boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- academy
create table public.academy_interest (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  club text check (char_length(club) <= 120),
  email text check (char_length(email) <= 254),
  phone text check (char_length(phone) <= 24),
  pathway public.academy_pathway not null,
  message text check (char_length(message) <= 2000),
  consent_at timestamptz not null default now(),
  handled boolean not null default false,
  created_at timestamptz not null default now(),
  check (email is not null or phone is not null)
);

-- ================================================================ RLS
alter table public.clubs enable row level security;
alter table public.profiles enable row level security;
alter table public.events enable row level security;
alter table public.payments enable row level security;
alter table public.event_registrations enable row level security;
alter table public.contributions enable row level security;
alter table public.academy_interest enable row level security;

-- clubs: public read, admin write
create policy clubs_read on public.clubs for select to anon, authenticated using (true);
create policy clubs_admin on public.clubs for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

-- events: published are public; admins see and write everything
create policy events_read on public.events for select to anon, authenticated
  using (status <> 'draft' or (select public.is_admin()));
create policy events_admin on public.events for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

-- profiles: own row (read/update), admins read all
create policy profiles_self_read on public.profiles for select to authenticated
  using (id = (select auth.uid()) or (select public.is_admin()));
create policy profiles_self_update on public.profiles for update to authenticated
  using (id = (select auth.uid())) with check (id = (select auth.uid()));
-- Column-level: users may only change these fields (not role / coach_tier).
revoke update on public.profiles from authenticated;
grant update (full_name, phone, club_id) on public.profiles to authenticated;

-- payments / registrations / contributions: owners read, server writes
create policy payments_own on public.payments for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));
create policy registrations_own on public.event_registrations for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));
create policy contributions_own on public.contributions for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));

-- academy_interest: no client access at all except admins reading/marking handled
create policy academy_admin_read on public.academy_interest for select to authenticated
  using ((select public.is_admin()));
create policy academy_admin_update on public.academy_interest for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

-- Defence in depth: clients never write money/identity tables directly.
revoke insert, update, delete on public.payments, public.event_registrations, public.contributions from anon, authenticated;
revoke insert, delete on public.academy_interest from anon, authenticated;
revoke all on public.academy_interest from anon;

-- ===== migrations/20261001000000_admin.sql
-- Admin view hardening.
-- Admins may only flip `handled` on leads; submitted content is immutable.
revoke update on public.academy_interest from authenticated;
grant update (handled) on public.academy_interest to authenticated;

-- Who handled a lead, and when (set by trigger, not by the client).
alter table public.academy_interest
  add column handled_at timestamptz,
  add column handled_by uuid references auth.users (id) on delete set null;

create or replace function public.stamp_lead_handled() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.handled is distinct from old.handled then
    new.handled_at := case when new.handled then now() end;
    new.handled_by := case when new.handled then (select auth.uid()) end;
  end if;
  return new;
end $$;
create trigger academy_interest_handled before update on public.academy_interest
  for each row execute function public.stamp_lead_handled();

create index academy_interest_created_idx on public.academy_interest (created_at desc);
create index contributions_created_idx on public.contributions (created_at desc);

-- ===== migrations/20261002000000_event_registration.sql
-- Events + registration.
-- All capacity / payment logic lives here so web and mobile behave identically
-- and races (two people taking the last spot) are impossible.

alter table public.events
  add column tag text,
  add column ends_at timestamptz,
  add column registration_opens_at timestamptz,
  add column registration_closes_at timestamptz,
  add column waiver_version text not null default '2026-10';

alter table public.event_registrations
  add column emergency_contact_name text check (char_length(emergency_contact_name) <= 120),
  add column emergency_contact_phone text check (char_length(emergency_contact_phone) <= 24),
  add column waiver_version text,
  add column adult_or_guardian_consent boolean not null default false,
  add column updated_at timestamptz not null default now();
create trigger registrations_touch before update on public.event_registrations
  for each row execute function public.touch_updated_at();
create index registrations_event_idx on public.event_registrations (event_id, status);

-- Unpaid "pending" registrations hold a spot for this long.
create or replace function public.registration_hold() returns interval
language sql immutable as $$ select interval '30 minutes' $$;

-- Spots taken = confirmed + recent pending.
create or replace function public.event_spots_taken(p_event uuid) returns int
language sql stable security definer set search_path = '' as $$
  select count(*)::int from public.event_registrations r
  where r.event_id = p_event
    and (r.status = 'confirmed'
         or (r.status = 'pending' and r.created_at > now() - public.registration_hold()));
$$;

-- Public, cheap availability for event pages (no personal data).
create or replace function public.event_availability(p_slug text)
returns table (capacity int, taken int)
language sql stable security definer set search_path = '' as $$
  select e.capacity, public.event_spots_taken(e.id) from public.events e
  where e.slug = p_slug and e.status = 'published';
$$;
grant execute on function public.event_availability(text) to anon, authenticated;

/**
 * Register a user. Called by the server with the service role after it has
 * authenticated the user. Returns the registration and, for paid events, the
 * pending payment it created (the server then signs a PayHere checkout).
 * Errors are raised with stable codes in the message: REG_<CODE>.
 */
create or replace function public.register_for_event(
  p_user uuid,
  p_slug text,
  p_category text,
  p_club uuid,
  p_emergency_name text,
  p_emergency_phone text,
  p_adult_or_guardian boolean,
  p_order_id text
) returns table (registration_id uuid, status public.registration_status, ticket_code text, payment_id uuid, amount numeric)
language plpgsql security definer set search_path = '' as $$
declare
  ev public.events;
  existing public.event_registrations;
  has_existing boolean;
  pay_id uuid;
  reg public.event_registrations;
begin
  -- Lock the event row: serialises concurrent registrations for this event.
  select * into ev from public.events where slug = p_slug for update;
  if not found or ev.status <> 'published' then raise exception 'REG_NOT_FOUND'; end if;
  if ev.registration_opens_at is not null and now() < ev.registration_opens_at then raise exception 'REG_NOT_OPEN'; end if;
  if ev.registration_closes_at is not null and now() > ev.registration_closes_at then raise exception 'REG_CLOSED'; end if;
  if ev.starts_at is not null and now() > ev.starts_at then raise exception 'REG_CLOSED'; end if;
  if cardinality(ev.categories) > 0 and (p_category is null or not (p_category = any (ev.categories))) then
    raise exception 'REG_BAD_CATEGORY';
  end if;
  if not p_adult_or_guardian then raise exception 'REG_CONSENT_REQUIRED'; end if;

  select * into existing from public.event_registrations where event_id = ev.id and user_id = p_user;
  has_existing := found; -- capture now: later statements overwrite FOUND
  if has_existing and (existing.status = 'confirmed'
                or (existing.status = 'pending' and existing.created_at > now() - public.registration_hold())) then
    raise exception 'REG_ALREADY_REGISTERED';
  end if;

  if ev.capacity is not null and public.event_spots_taken(ev.id) >= ev.capacity then
    raise exception 'REG_FULL';
  end if;

  if ev.fee_lkr > 0 then
    if p_order_id is null then raise exception 'REG_ORDER_REQUIRED'; end if;
    insert into public.payments (order_id, purpose, user_id, amount)
    values (p_order_id, 'registration', p_user, ev.fee_lkr)
    returning id into pay_id;
  end if;

  if has_existing then
    -- Re-registering after a cancelled/expired attempt: reuse the row (unique per event+user).
    update public.event_registrations r set
      category = p_category, club_id = p_club,
      emergency_contact_name = p_emergency_name, emergency_contact_phone = p_emergency_phone,
      adult_or_guardian_consent = p_adult_or_guardian,
      waiver_accepted_at = now(), waiver_version = ev.waiver_version,
      status = case when pay_id is null then 'confirmed'::public.registration_status else 'pending' end,
      payment_id = pay_id, created_at = now()
    where r.id = existing.id
    returning * into reg;
  else
    insert into public.event_registrations
      (event_id, user_id, category, club_id, emergency_contact_name, emergency_contact_phone,
       adult_or_guardian_consent, waiver_accepted_at, waiver_version, status, payment_id)
    values
      (ev.id, p_user, p_category, p_club, p_emergency_name, p_emergency_phone,
       p_adult_or_guardian, now(), ev.waiver_version,
       case when pay_id is null then 'confirmed'::public.registration_status else 'pending' end, pay_id)
    returning * into reg;
  end if;

  return query select reg.id, reg.status, reg.ticket_code, pay_id, ev.fee_lkr;
end $$;
revoke execute on function public.register_for_event(uuid, text, text, uuid, text, text, boolean, text) from public, anon, authenticated;
grant execute on function public.register_for_event(uuid, text, text, uuid, text, text, boolean, text) to service_role;

-- Payment outcome drives the registration (PayHere notify → payments.status).
create or replace function public.sync_registration_payment() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.purpose = 'registration' and new.status is distinct from old.status then
    update public.event_registrations set status =
      case when new.status = 'success' then 'confirmed'::public.registration_status
           when new.status in ('failed', 'cancelled', 'chargedback') then 'cancelled'
           else status end
    where payment_id = new.id;
  end if;
  return new;
end $$;
create trigger payments_sync_registration after update of status on public.payments
  for each row execute function public.sync_registration_payment();

-- Members may cancel their own registration (frees the spot); nothing else.
create or replace function public.cancel_my_registration(p_ticket text) returns boolean
language plpgsql security definer set search_path = '' as $$
declare n int;
begin
  update public.event_registrations r set status = 'cancelled'
  from public.events e
  where r.ticket_code = p_ticket and r.user_id = (select auth.uid()) and r.event_id = e.id
    and r.status <> 'cancelled' and (e.starts_at is null or e.starts_at > now());
  get diagnostics n = row_count;
  return n > 0;
end $$;
revoke execute on function public.cancel_my_registration(text) from public, anon;
grant execute on function public.cancel_my_registration(text) to authenticated;

-- Members can see which event a registration belongs to even after it's unpublished.
create policy events_registered_read on public.events for select to authenticated
  using (exists (select 1 from public.event_registrations r where r.event_id = events.id and r.user_id = (select auth.uid())));

-- ===== seed.sql
-- Member clubs (mirrors packages/core/src/content/clubs.ts)
insert into public.clubs (slug, name) values
  ('powertain-calisthenics', 'Powertain Calisthenics'),
  ('arcade-calisthenics', 'Arcade Calisthenics'),
  ('fitness-for-life', 'Fitness for Life'),
  ('nsbm-calisthenics-club', 'NSBM Calisthenics Club'),
  ('soul-lifters', 'Soul Lifters'),
  ('kalos-sthenos', 'Kalos Sthenos'),
  ('street-pump', 'Street Pump'),
  ('calisthenics-cartel', 'Calisthenics Cartel'),
  ('calisthenics-lk', 'Calisthenics LK'),
  ('mount-beach-cc', 'Mount Beach CC'),
  ('visal-gymnastx', 'Visal Gymnastx')
on conflict (slug) do nothing;

commit;
