#!/usr/bin/env bash
# Concatenate all migrations + seed into supabase/setup.sql, for pasting into
# Supabase → SQL Editor on a fresh project (alternative to `supabase db push`).
set -euo pipefail
cd "$(dirname "$0")/../supabase"
{
  echo "-- SLSWCA database setup — generated by scripts/bundle-sql.sh. Run ONCE on a fresh project."
  echo "-- Supabase → SQL Editor → New query → paste all → Run."
  echo "begin;"
  for f in migrations/*.sql; do echo; echo "-- ===== $f"; cat "$f"; done
  echo; echo "-- ===== seed.sql"; cat seed.sql
  echo; echo "commit;"
} > setup.sql
echo "wrote supabase/setup.sql ($(wc -l < setup.sql) lines)"
